### ISSUE TITLE
Can't open userPrefs in 'w+' mode

### ISSUE THREAD

**Issue by artofka** [mortentoo/maya#1]
When I execute script I have this error:
# Error: IOError: file C:/Users/User/Documents/maya/2018/scripts\fix_empty_shelves.py line 79: 22 # 

Something wrong when script try to open prefs file with 'w+' flag..
Path to file is right

**Comment by monoteba** [comment]
Updated the script just now. Can you try again? 

Do you supply the path manually, like `fix_empty_shelves("path/to/userPrefs.mel")` or do you just call `fix_empty_shelves()`?

**Comment by artofka** [comment]
Yes, of course! Thank you! I will try it in during of the day.

**Comment by artofka** [comment]
I was try to go run manual and automatically. I have the same error

**Comment by monoteba** [comment]
Can you post the error again, please? If it is the exact same error, you need to download the script from github again and replace the old one.

**Comment by artofka** [comment]
Sure! # Error: IOError: file D:/WORK/Proj/Dropbox Project Folder/project//Resources/Scripts\fix_empty_shelves.py line 86: 22 #

**Comment by artofka** [comment]
I already was replace this script

**Comment by monoteba** [comment]
Thanks, just wanted to be sure :)

**Comment by monoteba** [comment]
Ok, another attempt at fixing it. Here's the link [https://github.com/mortenblaa/maya/tree/master/scripts/utilities/fix_empty_shelves](https://github.com/mortenblaa/maya/tree/master/scripts/utilities/fix_empty_shelves)

**Comment by monoteba** [comment]
I think I've found the issue now. Can you let me know if it works for you?

**Comment by artofka** [comment]
Wow! Thank you so much! It works good right now.
